[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_VERSION = "20"
  YARN_FLAGS = "--ignore-engines"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
