[build]
  command = "node ./scripts/create-env.js && npm run build"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_VERSION = "18"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/graphql"
  to = "https://api.routine.familywealth.in/graphql"
  status = 200
  force = true