export const GC_USER_NAME = 'user-name'
export const GC_USER_EMAIL = 'user-email'
export const GC_PICTURE = 'user-picture'
export const GC_AUTH_TOKEN = 'auth-token'
export const GC_NOTIFICATION_TOKEN = 'notification-token'